### ISSUE TITLE
Using AWS SNS service on Azure cloud | getting com.amazonaws.SdkClientException: Unable to execute HTTP request

### ISSUE THREAD

**Issue by atakwale11** [aws/aws-sdk#317]
Hi Team,

Please note that we have our application deployed on Azure server. In our application we are using Amazon SNS service to send message. when we are trying to publish the message with the help of AWS SNS service we are getting below error. 
Please help to look into it and share the update on the same.

Error :
com.amazonaws.SdkClientException: Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1216)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1162)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)

**Comment by peterwoodworth** [comment]
Hey @atakwale11, what are you using to communicate with SNS, is it the Java SDK?

**Comment by atakwale11** [comment]
Yes! we are using java sdk.

**Comment by atakwale11** [comment]
Hi @peterwoodworth ,
Any update on above issue

**Comment by peterwoodworth** [comment]
@atakwale11 this repo is for issues which are affecting multiple SDKs (likely due to issues with the relevant service API). Since we're not sure what's causing this issue, the better place to report this would be to ask the Java SDK experts in the [Java repository](https://github.com/aws/aws-sdk-java/issues).

Also, it's hard for us to be able to help you if we don't have any code snippets which could be causing this error. Please share the code which you're using that generates this error. Thanks

**Comment by atakwale11** [comment]
Hi @peterwoodworth ,

Please note that we are using below function to send message.

snsClient.publish();

**Comment by peterwoodworth** [comment]
@atakwale11 could you please report this information in the Java repository? thanks
