### ISSUE TITLE
I am facing a issue using 'SpellCorrectionConfiguration' in Kendra Client query with boto3. 

### ISSUE THREAD

**Issue by vinayburam** [aws/aws-sdk#344]
Hi Team I am facing below issue when trying to query the kendra index using SpellCorrectionConfiguration= { 'IncludeQuerySpellCheckSuggestions': True })
////
code:
```python
kendra = boto3.client('kendra')
    kendra_index = os.environ['Kendra_index']
    spell_correction_configuration = { 'IncludeQuerySpellCheckSuggestions': True }
    response = kendra.query(IndexId=kendra_index,
                    QueryText=question,
                    QueryResultTypeFilter='QUESTION_ANSWER',
                    SpellCorrectionConfiguration= { 'IncludeQuerySpellCheckSuggestions': True })
```

Geeting below error:
```console
[ERROR] ParamValidationError: Parameter validation failed:
Unknown parameter in input: "SpellCorrectionConfiguration", must be one of: IndexId, QueryText, AttributeFilter, Facets, RequestedDocumentAttributes, QueryResultTypeFilter, DocumentRelevanceOverrideConfigurations, PageNumber, PageSize, SortingConfiguration, UserContext, VisitorId
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 386, in lambda_handler
    return dispatch(event)
  File "/var/task/lambda_function.py", line 351, in dispatch
    response = fulfillment_code_hook(intent_request)
  File "/var/task/lambda_function.py", line 283, in fulfillment_code_hook
    answers_list = get_kendra(intent_request, intent_request['inputTranscript'])
  File "/var/task/util.py", line 130, in get_kendra
    response = kendra.query(IndexId=kendra_index,
  File "/var/runtime/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 691, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/var/runtime/botocore/client.py", line 739, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/var/runtime/botocore/validate.py", line 360, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
```

Reference used - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kendra.html#kendra.Client.query

**Comment by vinayburam** [comment]
Can anyone  please help with this issue

**Comment by vinayburam** [comment]
@tim-finnigan  Could you please help me in this

**Comment by yenfryherrerafeliz** [comment]
Hi @vinayburam, thanks for opening this issue. I tried to reproduce the reported behavior but I was not able to. I actually looked [here](https://github.com/boto/botocore/blob/342f36c0e5d68f450e4baf64b22cfbbf5a824ba0/botocore/data/kendra/2019-02-03/service-2.json#L6187) where we can see that this parameter is a valid one for a query request.

For my reproduction I used the following environment details:
- Boto3 version 1.24.70
- Code to reproduce:
```python
import boto3

kendra = boto3.client('kendra', region_name='REGION')
kendra_index = 'INDEX-ID'
question = 'QUESTION' 
spell_correction_conf = { 'IncludeQuerySpellCheckSuggestions': True }
response = kendra.query(IndexId=kendra_index,
                    QueryText=question,
                    QueryResultTypeFilter='QUESTION_ANSWER',
                    SpellCorrectionConfiguration= { 'IncludeQuerySpellCheckSuggestions': True })

print(response)
```
Response I got:
```console
{'QueryId': 'QUERY-ID', 'ResultItems': [], 'FacetResults': [], 'TotalNumberOfResults': 0, 'ResponseMetadata': {'RequestId': 'REQUEST-ID', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'AMZ-REQUEST-ID', 'content-type': 'application/x-amz-json-1.1', 'content-length': '110', 'date': 'Mon, 12 Sep 2022 15:22:59 GMT'}, 'RetryAttempts': 0}}
```
So, sometimes the problem may be that you are using an outdated version of the SDK where this options is not yet available. Also, sometimes if you try to upgrade boto3 to the latest version you may get an error if you have the awscli and the new dependencies to be installed conflict with the requirements of the awscli, and in that case you need to first update the awscli and then boto3.

The way I upgraded it to the latest version was:
```console
pip3 install awscli --upgrade
pip3 install boto3 --upgrade
```

So, could you please check and try with the latest version of boto3?.

Thanks!

**Comment by vinayburam** [comment]
Thank you for your help , after adding new updated boto3 layer issue got resolved.

**Comment by yenfryherrerafeliz** [comment]
You are very welcome @vinayburam!
