### ISSUE TITLE
RestoreObjectCommand Malformed XML

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [aws/aws-sdk#505]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I get this error:
```MalformedXML: The XML you provided was not well-formed or did not validate against our published schema```
The restore doesn't happen

### SDK version number

@aws-sdk/package-name@version, ...

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.15.0

### Reproduction Steps

In `.env` have `AWS_REGION` as the AWS region.
```js
import {
  S3Client,
  RestoreObjectCommand,
  Tier
} from '@aws-sdk/client-s3'
import { config } from 'dotenv'
config()

const s3Client = new S3Client({
  region: process.env.AWS_REGION
})
await s3Client.send(new RestoreObjectCommand({
  Bucket: 'programmatically-created-bucket',
  Key: 'file.txt',
  RestoreRequest: {
    Days: 30,
    Tier: Tier.Bulk
  }
}))
```

### Observed Behavior

Error:
```js
/home/rajas/aws-playground/node_modules/.pnpm/@aws-sdk+smithy-client@3.296.0/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8
    const response = new exceptionCtor({
                     ^

MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
    at throwDefaultError (/home/rajas/aws-playground/node_modules/.pnpm/@aws-sdk+smithy-client@3.296.0/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_restXmlRestoreObjectCommandError (/home/rajas/aws-playground/node_modules/.pnpm/@aws-sdk+client-s3@3.299.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5975:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/rajas/aws-playground/node_modules/.pnpm/@aws-sdk+client-s3@3.299.0/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /home/rajas/aws-playground/node_modules/.pnpm/@aws-sdk+client-s3@3.299.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async /home/rajas/aws-playground/node_modules/.pnpm/@aws-sdk+client-s3@3.299.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /home/rajas/aws-playground/node_modules/.pnpm/@aws-sdk+client-s3@3.299.0/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
    at async /home/rajas/aws-playground/node_modules/.pnpm/@aws-sdk+client-s3@3.299.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async file:///home/rajas/aws-playground/repro.js:12:1 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'N8M7Z9KPAB9FJP3W',
    extendedRequestId: '5DHmRgSz8dv/TlHNPu2rPpRNvW+eIhSlzV1ujOIKrOn3SwzhThTKoeg5UxSnTkVZuDP9zy7VEWg=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'MalformedXML',
  RequestId: 'N8M7Z9KPAB9FJP3W',
  HostId: '5DHmRgSz8dv/TlHNPu2rPpRNvW+eIhSlzV1ujOIKrOn3SwzhThTKoeg5UxSnTkVZuDP9zy7VEWg='
}

Node.js v18.15.0
```

### Expected Behavior

The restore should happen, no error.

### Possible Solution

Maybe it's the logic for generating XML by the `RestoreObjectCommand`

**Comment by RanVaknin** [comment]
Hi there, 
I have received confirmation that an update of the S3 lifecycle documentation is now in the S3 team's queue. 
Since this is not actionable by the SDK team I'm going to go ahead and close this. 

please keep an eye of documentation changes for s3. 

Thanks again,
Ran~
