### ISSUE TITLE
Chime SDK Voice - ValidateE911Address API returns invalid country code

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-sdk#789]
Original issue: https://github.com/boto/boto3/issues/4216 (ref: V1461348548)

**Comment by cjhelloletsgo** [comment]
An update, this api considers roads with slashes to be invalid because it uses the regex pattern [\w ]+. This should be fixed. Here is an example of a valid address that is impossible to use:  2723 B 1/4 Rd, Grand Junction, CO 81503 (Random address off Zillow)

```python
import boto3

chime_sdk_voice_client = boto3.client("chime-sdk-voice")

chime_response = chime_sdk_voice_client.validate_e911_address(
    AwsAccountId="YOUR_ACCOUNT_ID_GOES_HERE",
    StreetNumber="2723",
    StreetInfo="B 1/4 Rd",
    City="Grand Junction",
    State="CO",
    Country="US",
    PostalCode="81503",
)

print(f"chime_response: {chime_response}")
```

```
Traceback (most recent call last):
  File "/home/colton/projects/work/firstfire/agero/test.py", line 5, in <module>
    chime_response = chime_sdk_voice_client.validate_e911_address(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colton/projects/work/firstfire/agero/.venv/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/colton/projects/work/firstfire/agero/.venv/lib/python3.12/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the ValidateE911Address operation: 1 validation error detected: Value at 'streetInfo' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w ]+
```

**Comment by tim-finnigan** [comment]
Thanks for following up, I have passed along that issue to the Chime SDK team as well. They have created a backlog item for further tracking of this. I reopened the original issue (https://github.com/boto/boto3/issues/4216) to continue tracking in GitHub.
