### ISSUE TITLE
BedrockAgentClient::startIngestionJob results in "Invalid timestamp value passed to DateTimeResult::fromTimestamp"

### ISSUE THREAD

**Issue by Saeven** [aws/aws-sdk#790]
**Environment**

PHP 7.4.33 (cli)
aws/aws-sdk-php 3.316.8

While invoking StartIngestionJob - the command succeeds, but an exception is thrown with this stack trace.

```
#0 /vendor/aws/aws-sdk-php/src/Api/Parser/JsonParser.php(60): Aws\Api\DateTimeResult::fromTimestamp('2024-07-25T20:5...', 'iso8601')
#1 /vendor/aws/aws-sdk-php/src/Api/Parser/JsonParser.php(27): Aws\Api\Parser\JsonParser->parse(Object(Aws\Api\TimestampShape), '2024-07-25T20:5...')
#2 /vendor/aws/aws-sdk-php/src/Api/Parser/JsonParser.php(27): Aws\Api\Parser\JsonParser->parse(Object(Aws\Api\StructureShape), Array)
#3 /vendor/aws/aws-sdk-php/src/Api/Parser/RestJsonParser.php(34): Aws\Api\Parser\JsonParser->parse(Object(Aws\Api\StructureShape), Array)
#4 /vendor/aws/aws-sdk-php/src/Api/Parser/AbstractRestParser.php(63): Aws\Api\Parser\RestJsonParser->payload(Object(GuzzleHttp\Psr7\Response), Object(Aws\Api\StructureShape), Array)
#5 /vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(126): Aws\Api\Parser\AbstractRestParser->__invoke(Object(Aws\Command), Object(GuzzleHttp\Psr7\Response))
#6 /vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(93): Aws\WrappedHttpHandler->parseResponse(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), Array)
#7 /vendor/guzzlehttp/promises/src/Promise.php(204): Aws\WrappedHttpHandler->Aws\{closure}(Object(GuzzleHttp\Psr7\Response))
#8 /vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#9 /vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#10 /vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(118): GuzzleHttp\Promise\TaskQueue->run()
#11 /vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(145): GuzzleHttp\Handler\CurlMultiHandler->tick()
#12 /vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#13 /vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#14 /vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#15 /vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#16 /vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#17 /vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#18 /vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
```

Examining key differences between successful calls and this calls at stack traces within the parser shows this:

Successful call:
<img width="376" alt="Screenshot 2024-07-25 at 4 54 24 PM" src="https://github.com/user-attachments/assets/318067fb-7811-4b2e-88ec-70c353a2b41e">

Failed call:
<img width="408" alt="Screenshot 2024-07-25 at 4 55 24 PM" src="https://github.com/user-attachments/assets/1f23577c-77b3-46f2-9711-73fc00aa86e0">

Others may be affected, but most S3 calls and such succeed.  It's just the Bedrock call that's tanking.

Thank you!
Alex

**Comment by Saeven** [comment]
Wrong project, brb.
